apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-zap-server.fullname" . }}-config
  labels:
    {{- include "mcp-zap-server.labels" . | nindent 4 }}
data:
  environment: {{ .Values.global.environment | quote }}
  zap-url: {{ .Values.mcp.zapClient.url | quote }}
  zap-port: {{ .Values.mcp.zapClient.port | quote }}
